services:
  - type: web
    name: shoppers-backend
    env: docker
    plan: free
    region: oregon
    rootDir: backend
    dockerfilePath: Dockerfile.simple
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://db.tjyvvreioqlpltyjukyc.supabase.co:5432/postgres
      - key: SPRING_DATASOURCE_USERNAME
        value: postgres
      - key: SPRING_DATASOURCE_PASSWORD
        value: Harsha9000513338
      - key: SHOOPERS_APP_JWT_SECRET
        value: YourVeryStrongJwtSecret
      - key: SHOOPERS_APP_JWT_EXPIRATION_MS
        value: "86400000"
      - key: SERVER_PORT
        value: "8080"
      - key: OAUTH_GOOGLE_CLIENT_ID
        value: YOUR_GOOGLE_CLIENT_ID
      - key: OAUTH_GOOGLE_CLIENT_SECRET
        value: YOUR_GOOGLE_CLIENT_SECRET
  - type: web
    name: shoppers-frontend
    env: node
    plan: free
    region: oregon
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npx serve -s dist -l 3000
    publishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://shoppers-backend.onrender.com/api